package mx.gob.sep.usicamm.reconocimientoproactividad.accesodatos.util;

/**
 *
 * @author albertosanchezlopez
 */
public enum SQL {
    SCHEMA;

    // --- Catalogos ---
    public static final String SQL_SEL_CAT_ENTIDADES="SELECT cve_entidad cve, descripcion_corta descripcion FROM cat_entidades_federativas WHERE cve_entidad<=32 ORDER BY descripcion;";
    public static final String SQL_SEL_CAT_SOSTENIMIENTOS="SELECT ES.cve_cat_tipo_sostenimiento cve, S.descripcion_corta descripcion FROM entidades_sostenimientos ES INNER JOIN cat_tipos_sostenimientos S ON ES.cve_cat_tipo_sostenimiento=S.cve_tipo_sostenimiento AND fecha_inicio_vigencia<=CURRENT_DATE() AND (fecha_fin_vigencia IS NULL OR fecha_fin_vigencia>=CURRENT_DATE) AND ES.cve_cat_entidad_federativa=? ORDER BY 2;";
    public static final String SQL_SEL_CAT_SERVICIOS="SELECT CONCAT(CMS.cve_cat_servicio_educativo, '-', CMS.cve_cat_modalidad) cve, CMS.descripcion_usuario descripcion FROM ctrl_cat_modalidades_servicios_educativos CMS WHERE CMS.cve_cat_sistema_informacion=? AND CMS.cve_cat_nivel_educativo=? ORDER BY 2;";
    public static final String SQL_SEL_CAT_CCT="SELECT cv_cct, c_nombre, inmueble_c_vialidad_principal, inmueble_c_nom_mun, inmueble_c_nom_loc, inmueble_n_extnum, contacto_c_telefono, c_tipo FROM cat_cct WHERE cv_cct=?;";
    // --- Catalogos ---

    
    // --- Usuario ---
    public static final String SQL_SEL_USUARIO="SELECT d.cve_docente, d.nombre, d.primer_apellido, d.segundo_apellido FROM docentes d WHERE d.curp=?";
    public static final String SQL_SEL_DOMINIOS="SELECT dominio_publico FROM balanceador WHERE cve_entidad=?";
    public static final String SQL_INS_LOG_ACCESO="INSERT INTO log_login(cve_sistema_informacion, solicitante, cve_estatus_login, ip_cliente, info_navegador, firma, de_prueba) VALUES (?, ?, ?, ?, ?, ?, ?);";
    public static final String SQL_SEL_PARAM="SELECT valor_entero FROM satap_parametros WHERE nombre_parametro=? AND cve_sistema_informacion=? AND fecha_inicio_vigencia<NOW() AND (fecha_fin_vigencia IS NULL OR fecha_fin_vigencia>NOW());";
    // --- Usuario ---

    
    // --- Docente ---
    public static final String SQL_SEL_DOCENTE_BY_CURP="SELECT D.cve_docente, D.curp, D.nombre, D.primer_apellido, D.segundo_apellido, (SELECT NT.numero_telefonico FROM numeros_telefonicos NT WHERE D.cve_docente=NT.cve_docente ORDER BY NT.fecha_creacion DESC limit 0,1) telefono1, (SELECT NT.numero_telefonico FROM numeros_telefonicos NT WHERE D.cve_docente=NT.cve_docente ORDER BY NT.fecha_creacion DESC limit 1,1) telefono2, (SELECT CE.correo_electronico FROM correos_electronicos CE WHERE D.cve_docente=CE.cve_docente ORDER BY CE.fecha_creacion DESC limit 0,1) correo1, (SELECT CE.correo_electronico FROM correos_electronicos CE WHERE D.cve_docente=CE.cve_docente ORDER BY CE.fecha_creacion DESC limit 1,1) correo2, CONCAT(DOM.calle, ' ', DOM.numero_exterior, ', Col. ', DOM.colonia, ', ', CM.descripcion_larga) domicilio, (SELECT GROUP_CONCAT(CCP.descripcion_larga) FROM rel_docentes_consideraciones_particulares RCP LEFT JOIN cat_consideraciones_particulares CCP ON RCP.cve_consideracion_particular=CCP.cve_consideracion_particular INNER JOIN ctrl_cat_consideraciones_particulares CC ON RCP.cve_consideracion_particular=CC.cve_cat_consideracion_particular AND CC.cve_cat_sistema_informacion=? WHERE RCP.cve_docente=D.cve_docente) consideraciones FROM docentes D LEFT JOIN domicilios DOM ON D.cve_docente=DOM.cve_docente LEFT JOIN cat_municipios CM ON DOM.cve_entidad=CM.cve_entidad AND DOM.cve_municipio=CM.cve_municipio WHERE D.curp=?;";
    // --- Docente ---

    
    // --- Registro ---
    public static final String SQL_INS_REGISTRO_PARTICIPACION="INSERT INTO registros_participantes(cve_cat_proceso, cve_cat_nivel_educativo, cve_cat_ciclo_escolar, cve_docente, cve_cat_entidad, cve_cat_municipio, cve_cat_tipo_sostenimiento, cve_cat_puesto_actual, cve_cat_servicio_educativo, cve_cat_modalidad, cve_cat_categoria_actual, cve_cat_tipo_evaluacion, cve_cat_tipo_plaza, cve_cat_cct, cve_cat_modalidad_tutoria, horas_plazas, cve_usuario_creador) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);";
    public static final String SQL_UPD_REGISTRO_PARTICIPACION="UPDATE registros_participantes SET cve_cat_tipo_sostenimiento=?, cve_cat_puesto_actual=?, cve_cat_servicio_educativo=?, cve_cat_modalidad=?, cve_cat_categoria_actual=?, cve_cat_tipo_evaluacion=?, cve_cat_tipo_plaza=?, cve_cat_cct=?, cve_cat_modalidad_tutoria=?, horas_plazas=? WHERE cve_cat_proceso=? AND cve_cat_nivel_educativo=? AND cve_cat_ciclo_escolar=? AND cve_docente=? AND cve_cat_entidad=?;";
    public static final String SQL_DEL_REGISTRO_PARTICIPACION="DELETE FROM registros_participantes WHERE cve_cat_proceso=? AND cve_cat_nivel_educativo=? AND cve_cat_ciclo_escolar=? AND cve_docente=? AND cve_cat_entidad=?;";
    public static final String SQL_SEL_REGISTRO_PARTICIPACION="SELECT RP.cve_docente, D.curp, D.nombre, D.primer_apellido, D.segundo_apellido, RP.cve_cat_entidad, CEF.descripcion_corta entidad, RP.cve_cat_municipio, CMU.descripcion_larga municipio, RP.cve_cat_tipo_sostenimiento, CTS.descripcion_corta sostenimiento, RP.cve_cat_puesto_actual, CP.descripcion_larga puesto_actual, RP.cve_cat_servicio_educativo, CS.descripcion_usuario servicio_educativo, RP.cve_cat_modalidad, RP.cve_cat_categoria_actual, CC.descripcion_larga categoria_actual, RP.cve_cat_tipo_evaluacion, CTE.descripcion_larga valoracion, RP.cve_cat_tipo_plaza, CTP.descripcion_larga tipo_plaza, RP.cve_cat_modalidad_tutoria, CMT.descripcion_larga modalidad_tutoria, RP.horas_plazas, RP.cve_cat_estatus_registro, RP.folio, RP.huella, RP.fecha_registro, RP.cve_docente_registra, DU.nombre nombre_usuario, DU.primer_apellido p_apellido_usuario, DU.segundo_apellido s_apellido_usuario FROM registros_participantes RP INNER JOIN docentes D ON RP.cve_docente=D.cve_docente INNER JOIN cat_entidades_federativas CEF ON RP.cve_cat_entidad=CEF.cve_entidad LEFT JOIN cat_municipios CMU ON RP.cve_cat_municipio=CMU.cve_municipio AND RP.cve_cat_entidad=CMU.cve_entidad INNER JOIN cat_tipos_sostenimientos CTS ON RP.cve_cat_tipo_sostenimiento=CTS.cve_tipo_sostenimiento INNER JOIN cat_puestos CP ON RP.cve_cat_puesto_actual=CP.cve_puesto INNER JOIN ctrl_cat_modalidades_servicios_educativos CS ON CS.cve_cat_sistema_informacion=? AND RP.cve_cat_servicio_educativo=CS.cve_cat_servicio_educativo AND RP.cve_cat_modalidad=CS.cve_cat_modalidad AND RP.cve_cat_nivel_educativo=CS.cve_cat_nivel_educativo LEFT JOIN cat_categorias CC ON RP.cve_cat_categoria_actual=CC.cve_categoria INNER JOIN cat_tipos_evaluaciones CTE ON RP.cve_cat_tipo_evaluacion=CTE.cve_tipo_evaluacion LEFT JOIN cat_tipo_plaza CTP ON RP.cve_cat_tipo_plaza=CTP.cve_tipo_plaza LEFT JOIN tutoria_cat_modalidad_tutoria CMT ON RP.cve_cat_modalidad_tutoria=CMT.cve_modalidad_tutoria LEFT JOIN docentes DU ON RP.cve_docente_registra=DU.cve_docente WHERE RP.cve_cat_proceso=? AND RP.cve_cat_nivel_educativo=? AND RP.cve_cat_ciclo_escolar=? AND RP.cve_docente=?;";
    public static final String SQL_BIT_REGISTRO_PARTICIPACION="INSERT INTO bitacora_abc_sistemas(nombre_tabla, cve_sistema_informacion, cve_tipo_movimiento, cve_docente_modificada, cve_docente_quien_modifica, atributos) SELECT 'registros_participantes', ?, ?, ?, ?, JSON_OBJECT('rid', rid, 'cve_docente', cve_docente, 'cve_cat_proceso', cve_cat_proceso, 'cve_cat_nivel_educativo', cve_cat_nivel_educativo, 'cve_cat_ciclo_escolar', cve_cat_ciclo_escolar, 'cve_cat_entidad', cve_cat_entidad, 'cve_cat_municipio', cve_cat_municipio, 'cve_cat_tipo_evaluacion', cve_cat_tipo_evaluacion, 'cve_cat_subsistema', cve_cat_subsistema, 'cve_cat_puesto_actual', cve_cat_puesto_actual, 'cve_cat_puesto_aspira', cve_cat_puesto_aspira, 'cve_cat_cct', cve_cat_cct, 'cve_cat_tipo_sostenimiento', cve_cat_tipo_sostenimiento, 'cve_cat_servicio_educativo', cve_cat_servicio_educativo, 'cve_cat_modalidad', cve_cat_modalidad, 'cve_cat_categoria_actual', cve_cat_categoria_actual, 'cve_cat_categoria_aspira', cve_cat_categoria_aspira, 'cve_cat_tipo_plaza', cve_cat_tipo_plaza, 'cve_cat_entidad_participacion', cve_cat_entidad_participacion, 'cve_cat_cct_promocion', cve_cat_cct_promocion, 'cve_cat_modalidad_tutoria', cve_cat_modalidad_tutoria, 'horas_plazas', horas_plazas, 'cve_cat_estatus_registro', cve_cat_estatus_registro, 'folio', folio, 'huella', huella, 'cve_usuario_creador', cve_usuario_creador, 'cve_docente_registra', cve_docente_registra, 'fecha_cambio_estatus', fecha_cambio_estatus, 'fecha_creacion', fecha_creacion, 'fecha_ultima_actualizacion', fecha_ultima_actualizacion) json FROM registros_participantes WHERE cve_cat_proceso=? AND cve_cat_nivel_educativo=? AND cve_cat_ciclo_escolar=? AND cve_docente=? AND cve_cat_entidad=? LIMIT 1;";
    // --- Registro ---
}


